language: php

php:
  - 5.6

env:
  global:
    - APP_ENV=staging
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
