language: php

php:
  - 5.6
  - 7.0

addons:
  mariadb: '10.0'
  code_climate:
        repo_token: f40548b34916a3abaae2a41c65892272fde61d0885efb93b9e2f3e15dc44b68a

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_DATABASE=test
    - DB_USERNAME=root

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_success:
  - wget $SUCCESS_HOOK
