language: php

php:
  - 5.6
  - 7.0

addons:
  mariadb: '10.0'

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=xxxx
    - DB_DATABASE=test
    - DB_USERNAME=root

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
